package cmd

import "fmt"

// ShowUsage Display help message (moved from main.go)
func ShowUsage() {
	fmt.Println("🚀 AI Parallel Development Team - Integrated Launch System")
	fmt.Println("")
	fmt.Println("Usage:")
	fmt.Println("  claude-squad <session-name> [options]")
	fmt.Println("  claude-squad [management-commands]")
	fmt.Println("")
	fmt.Println("Arguments:")
	fmt.Println("  session-name     tmux session name (required)")
	fmt.Println("  ")
	fmt.Println("Options:")
	fmt.Println("  --reset          Delete existing session and recreate")
	fmt.Println("  --verbose, -v    Enable verbose logging")
	fmt.Println("  --debug, -d      Enable debug logging")
	fmt.Println("  --silent, -s     Silent mode (minimize log output)")
	fmt.Println("  --help           Show this help")
	fmt.Println("")
	fmt.Println("Management Commands:")
	fmt.Println("  --list             Show running AI team sessions")
	fmt.Println("  --delete [name]    Delete specified session")
	fmt.Println("  --delete-all       Delete all AI team sessions")
	fmt.Println("  --show-config      Show configuration summary")
	fmt.Println("  --config [session] Show detailed configuration")
	fmt.Println("  --generate-config  Generate configuration file template")
	fmt.Println("    --force          Overwrite existing files")
	fmt.Println("  --init [ja|en]     Initialize system (create directories and config files)")
	fmt.Println("    --force          Overwrite existing files during initialization")
	fmt.Println("")
	fmt.Println("  --doctor           Run system health check")
	fmt.Println("")
	fmt.Println("Examples:")
	fmt.Println("  claude-squad myproject               # Launch integrated monitoring with myproject session")
	fmt.Println("  claude-squad ai-team                 # Launch integrated monitoring with ai-team session")
	fmt.Println("  claude-squad myproject --reset       # Recreate myproject session")
	fmt.Println("  claude-squad myproject --verbose     # Launch with verbose logging")
	fmt.Println("  claude-squad myproject --silent      # Launch in silent mode")
	fmt.Println("  claude-squad --list                    # Show session list")
	fmt.Println("  claude-squad --delete myproject        # Delete myproject session")
	fmt.Println("  claude-squad --delete-all              # Delete all sessions")
	fmt.Println("  claude-squad --show-config             # Show configuration summary")
	fmt.Println("  claude-squad --config ai-team          # Show detailed configuration for ai-team session")
	fmt.Println("  claude-squad --generate-config         # Generate configuration file template")
	fmt.Println("  claude-squad --generate-config --force # Overwrite and generate configuration file")
	fmt.Println("  claude-squad --init ja                 # Initialize system with Japanese instructions")
	fmt.Println("  claude-squad --init en                 # Initialize system with English instructions")
	fmt.Println("  claude-squad --init ja --force         # Overwrite and initialize with Japanese instructions")
	fmt.Println("")
	fmt.Println("  claude-squad --doctor                  # Run system health check")
	fmt.Println("")
	fmt.Println("Environment Variables:")
	fmt.Println("  VERBOSE=true       Enable verbose logging")
	fmt.Println("  SILENT=true        Enable silent mode")
	fmt.Println("")
}
